name: Staging CI - Build and test on staging branch
on:
  push:
    branches: [ staging ]
  pull_request: 
    branches: [ staging ]

jobs:
  CI: 
    runs-on: ubuntu-latest
    name: Build sln on ubuntu-latest and run unit tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: staging

      - name: Set up .Net 5.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

      - name: Build sln
        run: dotnet build KNet/KNet.sln

      - name: Run Unit Tetsts
        run: dotnet test KNet/KNet.APITests/KNet.APITests.csproj
        
