name: .NET 5

on:
  push:
    branches: [ main ]
  pull_request: 
    branches: [ main ]

jobs:
  build:    
    runs-on: ubuntu-latest
    name: Run on ubuntu-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET 5.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.100-rc.1.20452.10'

      - name: Install dependencies
        run: dotnet restore

      - name: Build - Debug
        run: dotnet build --configuration Release --no-restore
