name: .NET 5

on:
  push:
    branches: [ main ]
  pull_request: 
    branches: [ main ]

jobs:
  build:    
    runs-on: ubuntu-latest
    name: Run on ubuntu-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v2


