name: Linux Container 

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: azure/docker-login@v1
      with:
        login-server: mycontainer.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build -f KNet/KNet.API/Dockerfile . -t knetregistry.azurecr.io:${{ github.sha }} 
        docker push knetregistry.azurecr.io:${{ github.sha }}  
