name: .NET 5

on:
  push:
    branches: [ main ]
  pull_request: 
    branches: [ main ]

jobs:
  build:    
    runs-on: ubuntu-latest
    name: Run on ubuntu-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up .Net 5.0
        uses: actions/setup-dotnet@v1
        with:
            dotnet-version: '5.0.x'
            
      - name: Install dependencies
        run: dotnet restore
        
      - run: dotnet build ./KNet/KNet.sln
